services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity

    user: "1000"
    privileged: true
    environment:
      - SHELL=/bin/zsh

    volumes:
      - command.history:/commandhistory

      - ..:/workspace
      - ${HOME}/workspaces:/workspaces

    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G
          pids: 2048
        reservations:
          cpus: "2"
          memory: 4G

volumes:
  command.history:
