enum Codes {
	BLOB_UNKNOWN = 1,
	BLOB_UPLOAD_INVALID = 2,
	BLOB_UPLOAD_UNKNOWN = 3,
	DIGEST_INVALID = 4,
	MANIFEST_BLOB_UNKNOWN = 5,
	MANIFEST_INVALID = 6,
	MANIFEST_UNKNOWN = 7,
	NAME_INVALID = 8,
	NAME_UNKNOWN = 9,
	SIZE_INVALID = 10,
	UNAUTHORIZED = 11,
	DENIED = 12,
	UNSUPPORTED = 13,
	TOOMANYREQUESTS = 14,
}

export default Codes
